/**
 * AURA — 20 Aesthetic Music Worlds Dataset
 * Personalized Music Gift Edition
 */

const FINAL_MESSAGE = {
  title: "you found them all ♡",
  subtitle: "20 / 20 little worlds unlocked",
  badge: "✦ secret unlocked ✦",
  letter: `Hey you,

If you are reading this, it means you took the time to explore every single little world and listen to every melody.

I created this little corner of the internet just for you — a cozy sanctuary you can always come back to whenever you want to unwind, escape the noise of the world, or just listen to beautiful music under the stars.

Every song in here has a little piece of warmth meant to make your day softer and brighter. Thank you for listening, and thank you for being you.

Forever your biggest fan ♡`
};

const SONGS_DATA = [
  {
    id: 1,
    title: "Samjhawan",
    artist: "Arijit Singh & Shreya Ghoshal",
    album: "Humpty Sharma Ki Dulhania",
    worldName: "Himalayan Twilight Valley",
    mood: "Soulful & Melancholic",
    badge: "Amber Twilight",
    tagPhrase: "made for you",
    note: "This melody always feels like a warm cup of chai on a rainy evening. I hope it brings peace to your mind whenever things feel overwhelming ♡",
    image: "assets/images/world_01.jpg",
    audioSrc: "assets/audio/track_01.mp3",
    quote: "Main tenu samjhawan ki, na tere bina lagda jee...",
    translation: "How do I make you understand, my heart finds no peace without you...",
    lore: "Resting beside a serene alpine lake tucked between mist-laden Himalayan peaks, where the evening dusk washes the pine trees in liquid amber gold.",
    theme: {
      primary: "#f59e0b",
      accent: "#fbbf24",
      bgGradient: "linear-gradient(135deg, #1c140e 0%, #2e1a0d 50%, #0a0e17 100%)",
      glowColor: "rgba(245, 158, 11, 0.45)"
    },
    audio: {
      ambientType: "wind_pine"
    },
    lyrics: [
      "✦ Instrumental Acoustic Intro ✦",
      "Nahi jeena tere baajon, nahi jeena...",
      "Main tenu samjhawan ki",
      "Na tere bina lagda jee",
      "Tu ki jaane pyar mera",
      "Main karaan intezar tera",
      "Tu dil tui-yon jaan meri",
      "Jaan meri... jaan meri...",
      "✦ Sitar & Flute Interlude ✦",
      "Mere dil vich rehan waleye",
      "Kyun door gaye khwaab sajaye",
      "Dillan de sode kade hunde nahi",
      "Dillan de nate kade mukkde nahi",
      "Ve maahi ve maahi ve...",
      "Akhaan cho neer vage",
      "Tere bin na saah chalde",
      "Main tenu samjhawan ki",
      "Na tere bina lagda jee",
      "Tu dil tui-yon jaan meri",
      "Jaan meri... jaan meri...",
      "✦ Violin & Piano Melodies ✦",
      "Kade aa mil sajjna ve",
      "Tenu khol ke dassiye dil da haal",
      "Muk gaye sab dukhde mere",
      "Jadon hove tu mere naal",
      "Main karaan intezar tera",
      "Main tenu samjhawan ki",
      "Na tere bina lagda jee",
      "Tu dil tui-yon jaan meri",
      "Jaan meri... jaan meri...",
      "✦ Fade Out & Mountain Breeze ✦"
    ]
  },
  {
    id: 2,
    title: "O Meri Laila",
    artist: "Jyotica Tangri & Atif Aslam",
    album: "Laila Majnu",
    worldName: "Oasis of Thousand Lanterns",
    mood: "Mystical & Passionate",
    badge: "Desert Mirage",
    tagPhrase: "for late nights",
    note: "This song has so much soul. Play this when the night gets quiet and you want to drift into a dreamland full of stars ♡",
    image: "assets/images/world_02.jpg",
    audioSrc: "assets/audio/track_02.mp3",
    quote: "O meri Laila, khwab tu hai pehla...",
    translation: "O my beloved Laila, you are the first dream my soul ever dreamed...",
    lore: "Endless golden sand dunes illuminated by brass lanterns under a celestial violet milky way, whispering timeless desert legends across the starlit oasis.",
    theme: {
      primary: "#c084fc",
      accent: "#f59e0b",
      bgGradient: "linear-gradient(135deg, #1c0f2b 0%, #2a1138 50%, #15091f 100%)",
      glowColor: "rgba(192, 132, 252, 0.45)"
    },
    audio: {
      ambientType: "desert_breeze"
    },
    lyrics: [
      "✦ Mystical Rubab & Oud Intro ✦",
      "O meri Laila, khwab tu hai pehla",
      "Kaisa yeh khumar tera, kaisa nasha",
      "Teri aankhon ke darya mein kho gaya",
      "Main toh tera deewana ho gaya",
      "Poocho na haal mera, kya se kya ho gaya",
      "O meri Laila... o meri Laila...",
      "✦ Desert Mirage Strings ✦",
      "Tu meri rooh ki pyas hai",
      "Har pal tu mere paas hai",
      "Yeh ishq nahi aasan bas itna samajh lijiye",
      "Ik aag ka darya hai aur doob ke jaana hai",
      "O meri Laila, khwab tu hai pehla",
      "Kaisa yeh khumar tera, kaisa nasha",
      "✦ Passionate Orchestral Bridge ✦",
      "Sufi jigar se nikli dua tu",
      "Mera jahaan hai, mera khuda tu",
      "Tere bina main adhoora sa lafz hoon",
      "Poocho na haal mera, kya se kya ho gaya",
      "O meri Laila... o meri Laila...",
      "Main toh tera deewana ho gaya",
      "O meri Laila, khwab tu hai pehla...",
      "✦ Starlit Oasis Echoes ✦"
    ]
  },
  {
    id: 3,
    title: "Aarzu",
    artist: "Asim Azhar, Noor, Khan & Madhurxo",
    album: "Aarzu - Single",
    worldName: "Cherry Blossom Dusk Courtyard",
    mood: "Ethereal & Dreamy",
    badge: "Sakura Glow",
    tagPhrase: "just because",
    note: "Soft and gentle, just like spring petals falling. Whenever you listen to this, remember how special you truly are ♡",
    image: "assets/images/world_03.jpg",
    audioSrc: "assets/audio/track_03.mp3",
    quote: "Tere bina lagta nahi mera jiya, kyun bhala...",
    translation: "Without you, my restless soul wanders in solitary stillness...",
    lore: "A tranquil dusk tea courtyard surrounded by blooming cherry blossoms and glowing stone lanterns, where gentle pink petals float upon still koi waters.",
    theme: {
      primary: "#f472b6",
      accent: "#fbcfe8",
      bgGradient: "linear-gradient(135deg, #27101f 0%, #3b182d 50%, #120e1b 100%)",
      glowColor: "rgba(244, 114, 182, 0.45)"
    },
    audio: {
      ambientType: "zen_water"
    },
    lyrics: [
      "✦ Gentle Acoustic Guitar Intro ✦",
      "Tere bina lagta nahi mera jiya, kyun bhala",
      "Aarzu hai bas teri, tu hi meri dastaan",
      "Kyun faasle darmiyaan hain yahan",
      "Aa bhi jaa tu mere sang yahan",
      "Raahon mein bikhre hain khwab mere",
      "Dhoonde tujhe yeh nigahein meri",
      "Aarzu hai bas teri, aarzu hai bas teri...",
      "✦ Cherry Blossom Melody Interlude ✦",
      "Shaam dhal rahi hai teri yaad mein",
      "Khamosh baitha hoon fariyad mein",
      "Kash tu laut aaye iss mod par",
      "Chhod ke na jaana tanha tod kar",
      "Tere bina lagta nahi mera jiya",
      "Aarzu hai bas teri, tu hi meri dastaan",
      "Aarzu hai bas teri... aarzu hai bas teri...",
      "Aa bhi jaa tu mere sang yahan...",
      "✦ Soft Koi Ripple Outro ✦"
    ]
  },
  {
    id: 4,
    title: "Maskara",
    artist: "A.R. Rahman, Vedang Raina & Nilanjana",
    album: "Main Vaapas Aaunga",
    worldName: "Punjab Golden Hour",
    mood: "Warm & Nostalgic",
    badge: "Punjab Pind",
    tagPhrase: "keep this one ♡",
    note: "The golden warmth of a village sunset, sarson fields, and nostalgic folk beats. It’s got that cozy, happy energy you deserve every single day ♡",
    image: "assets/images/world_04.jpg",
    audioSrc: "assets/audio/track_04.mp3",
    quote: "Akhaan vich paaya mascara jachda, dil tere naal ve main jod rakheya...",
    translation: "Golden sunset illuminates the blooming mustard fields, while the warmth of village love resonates across the courtyard...",
    lore: "A picturesque traditional Punjabi pind at golden twilight dusk, surrounded by lush blooming mustard fields, rustic brick courtyards, vibrant swirling phulkari dupattas, and warm harmonium melodies echoing across the sunset.",
    theme: {
      primary: "#f59e0b",
      accent: "#f43f5e",
      bgGradient: "linear-gradient(135deg, #2b180d 0%, #3e2210 50%, #20101b 100%)",
      glowColor: "rgba(245, 158, 11, 0.55)"
    },
    audio: {
      ambientType: "sunset_harmonium"
    },
    lyrics: [
      "✦ Folk Harmonium & Tumbi Alaap ✦",
      "Akhaan vich paaya mascara jachda",
      "Dil tere naal ve main jod rakheya",
      "Golden sunbeams dancing on the mustard fields",
      "Every heartbeat whispers what the spirit feels",
      "Tere bina chain nahi aunda ve",
      "Har pal tera chehra sataunda ve",
      "Maskara tera kamaal lagda",
      "Dil mera behaal lagda...",
      "✦ Saffron Sunset Flute & Dholak Groove ✦",
      "Village twilight glowing warm and bright",
      "You and I dancing in the golden light",
      "Pind diyan galiyan vich tera hi naad hai",
      "Har ik saah vich teri hi yaad hai",
      "Akhaan vich paaya mascara jachda",
      "Dil tere naal ve main jod rakheya",
      "Maskara tera kamaal lagda...",
      "Har pal tera chehra sataunda ve...",
      "✦ Evening Dusk & Harmonium Fade ✦"
    ]
  },
  {
    id: 5,
    title: "Thinking of You",
    artist: "AP Dhillon",
    album: "Live Performance",
    worldName: "Sunset Shoreline Solitude",
    mood: "Nostalgic & Reflective",
    badge: "Golden Sunset Shore",
    tagPhrase: "our little song",
    note: "Watching the tide roll in under an amber sky. Whenever you hear this, know someone is thinking of you with the biggest smile ♡",
    image: "assets/images/world_05.jpg",
    audioSrc: "assets/audio/track_05.mp3",
    quote: "Thinking of you every minute that goes by...",
    translation: "Sitting quietly by the ocean tide as memories reflect like liquid gold across the waves...",
    lore: "Sitting quietly by the rolling ocean tide as the sun dips below the horizon, bathed in amber gold and twilight reflections across the endless waves.",
    theme: {
      primary: "#f59e0b",
      accent: "#fdba74",
      bgGradient: "linear-gradient(135deg, #2b180d 0%, #3d2112 50%, #151d2c 100%)",
      glowColor: "rgba(245, 158, 11, 0.45)"
    },
    audio: {
      ambientType: "ocean_breeze"
    },
    lyrics: [
      "✦ Sunset Ocean Keys Intro ✦",
      "Thinking of you every minute that goes by",
      "Watching the ocean tide meet the twilight sky",
      "Memories drift like gold upon the sea",
      "Wishing that you were right here with me",
      "Late night drives under the city lights",
      "Remembering those unforgettable nights",
      "Girl you know you're always on my mind",
      "A love like yours is hard to find...",
      "✦ Guitar Chords & Waves ✦",
      "Waves keep crashing against the shore",
      "Missing you now more than ever before",
      "Golden reflections across the sand",
      "Holding memories inside my hand",
      "Thinking of you every minute that goes by",
      "Wishing that you were right here with me...",
      "✦ Amber Dusk Fade ✦"
    ]
  },
  {
    id: 6,
    title: "Boyfriend",
    artist: "Karan Aujla ft. Sunanda Sharma",
    album: "Boyfriend - Single (Prod. Ikky)",
    worldName: "Miami Art-Deco Sunset Terrace",
    mood: "Playful & Vibrant",
    badge: "Coastal Sunset",
    tagPhrase: "made to make you smile",
    note: "Pure upbeat sunset drive vibes! Play this with the windows down and sing along as loud as you want ♡",
    image: "assets/images/world_06.jpg",
    audioSrc: "assets/audio/track_06.mp3",
    quote: "Karan Aujla & Sunanda vibe on a summer evening drive...",
    translation: "Warm evening ocean breeze, palm shadows, and carefree coastal sunset memories...",
    lore: "An elegant Art-Deco oceanfront terrace bathed in coral sunset tones, looking out upon the turquoise Caribbean tide and swaying palm fronds.",
    theme: {
      primary: "#fb923c",
      accent: "#2dd4bf",
      bgGradient: "linear-gradient(135deg, #291811 0%, #381f14 50%, #0d2826 100%)",
      glowColor: "rgba(251, 146, 60, 0.45)"
    },
    audio: {
      ambientType: "ocean_breeze"
    },
    lyrics: [
      "✦ Ikky Tropical Bass Intro ✦",
      "Karan Aujla on the beat, Ikky vibe",
      "Gaddi vich baith ke cruise karde",
      "Coastal sunset glowing in your eyes",
      "No more drama, no goodbyes",
      "Tu meri queen, main tera king soniye",
      "Duniya nu bhul ke tu nach soniye",
      "Ocean breeze blowing through your hair",
      "Vibe check passed, nothing can compare...",
      "✦ Coral Art-Deco Beat Drop ✦",
      "Boyfriend tera poora hit balliye",
      "Style sadda har thaan lit balliye",
      "Gaddi vich baith ke cruise karde",
      "Coastal sunset glowing in your eyes",
      "Boyfriend tera poora hit balliye...",
      "✦ Miami Sunset Fade Out ✦"
    ]
  },
  {
    id: 7,
    title: "Wavy",
    artist: "Karan Aujla",
    album: "Wavy (Prod. Ikky)",
    worldName: "Bioluminescent Abyssal Deep",
    mood: "Electric & Mesmerizing",
    badge: "Ocean Luminescence",
    tagPhrase: "for midnight drives",
    note: "Submerged deep underwater where everything glows electric cyan. Put on your headphones and let the bass take over ♡",
    image: "assets/images/world_07.jpg",
    audioSrc: "assets/audio/track_07.mp3",
    quote: "Vibe meri wavy ae, look poori crazy ae...",
    translation: "Riding effortless waves through neon currents beneath the midnight tide...",
    lore: "Submerged deep into the oceanic abyss where glowing bioluminescent jellyfish pulse softly beside vibrant radiant coral sanctuaries.",
    theme: {
      primary: "#38bdf8",
      accent: "#818cf8",
      bgGradient: "linear-gradient(135deg, #07192f 0%, #0c2b4e 50%, #051329 100%)",
      glowColor: "rgba(56, 189, 248, 0.5)"
    },
    audio: {
      ambientType: "deep_water"
    },
    lyrics: [
      "✦ Deep Aqua Sub-Bass Intro ✦",
      "Vibe meri wavy ae, look poori crazy ae",
      "Gaddi meri low, cruise karde slow",
      "Neon glowing under the midnight flow",
      "Drip poori tight, everything feels right",
      "Riding effortless waves through the deep",
      "Promises we make and promises we keep",
      "Abyssal glow shining bright in the dark",
      "Setting the night ablaze with a spark...",
      "✦ Bioluminescent Wave Groove ✦",
      "Wavy look, wavy flow",
      "Everywhere we go, we put on a show",
      "Vibe meri wavy ae, look poori crazy ae",
      "Gaddi meri low, cruise karde slow...",
      "✦ Ocean Abyss Echo ✦"
    ]
  },
  {
    id: 8,
    title: "For a Reason",
    artist: "Karan Aujla ft. Tania",
    album: "For A Reason (Prod. Ikky)",
    worldName: "Golden Sunflower Fields",
    mood: "Uplifting & Warm",
    badge: "Sunflower Glow",
    tagPhrase: "always remember",
    note: "Everything really does happen for a reason. Better days, brighter sunsets, and so much happiness ahead of you ♡",
    image: "assets/images/world_08.jpg",
    audioSrc: "assets/audio/track_08.mp3",
    quote: "Everything that happens, happens for a reason...",
    translation: "Every moment that passes, every turning season carries its own divine destiny...",
    lore: "Vast blooming sunflower fields basking in the golden sunbeams, radiating warmth, positivity, and the quiet assurance that everything aligns in time.",
    theme: {
      primary: "#eab308",
      accent: "#facc15",
      bgGradient: "linear-gradient(135deg, #281f08 0%, #3f310d 50%, #182315 100%)",
      glowColor: "rgba(234, 179, 8, 0.45)"
    },
    audio: {
      ambientType: "meadow_wind"
    },
    lyrics: [
      "✦ Golden Acoustic Intro ✦",
      "Everything that happens, happens for a reason",
      "Golden sunflowers dancing through the season",
      "Waqt de naal sab theek ho janda",
      "Dil da dard vi mit janda",
      "Sunbeams breaking through the morning sky",
      "No more tears left in the eye",
      "Trust the journey, let it unfold",
      "Every silver lining turns to gold...",
      "✦ Meadow Sunflower Strings ✦",
      "Rab te bharosa rakh tu soniye",
      "Zindagi haseen ban jau soniye",
      "Har ik mod te umeed da deep jale",
      "Jadon tu mere naal naal chale",
      "Everything that happens, happens for a reason",
      "Every silver lining turns to gold...",
      "✦ Golden Horizon Breeze ✦"
    ]
  },
  {
    id: 9,
    title: "Afreen Afreen",
    artist: "Rahat Fateh Ali Khan & Momina Mustehsan",
    album: "Coke Studio Season 9",
    worldName: "Royal Mughal Starlight Pavilion",
    mood: "Classical & Sublime",
    badge: "Celestial Pearl",
    tagPhrase: "pure magic",
    note: "A masterpiece of divine poetry and silver moonbeams. This one is as timeless as your charm ♡",
    image: "assets/images/world_09.jpg",
    audioSrc: "assets/audio/track_09.mp3",
    quote: "Husn-e-jaana ki tareef mumkin nahi, afreen afreen...",
    translation: "Praise of such celestial beauty defies all words; praised be the divine grace...",
    lore: "A majestic ivory marble pavilion overlooking mirror-still starlit fountains under the silver glow of a crescent moon in ancient Agra.",
    theme: {
      primary: "#e2e8f0",
      accent: "#fbbf24",
      bgGradient: "linear-gradient(135deg, #131722 0%, #202738 50%, #181d29 100%)",
      glowColor: "rgba(226, 232, 240, 0.4)"
    },
    audio: {
      ambientType: "fountain_night"
    },
    lyrics: [
      "✦ Traditional Harmonium & Tabla Alaap ✦",
      "Aisa dekha nahi khoobsurat koi",
      "Jism jaise ajanta ki murat koi",
      "Jism jaise nigaahon pe jaadu koi",
      "Jism naghma koi, jism khushbu koi",
      "Husn-e-jaana ki tareef mumkin nahi",
      "Afreen afreen, afreen afreen...",
      "Tu bhi dekhe agar toh kahe humnasheen",
      "Afreen afreen, afreen afreen...",
      "✦ Momina & Rahat Vocal Jugalbandi ✦",
      "Chehra ik phool ki tarah shadaab hai",
      "Chehra uska hai ya koi mahtab hai",
      "Aankhon mein nasha jaise sharab hai",
      "Husn-e-jaana ki tareef mumkin nahi",
      "Afreen afreen, afreen afreen...",
      "✦ Qawwali Claps & Rhythmic Swells ✦",
      "Jaane kaisi bandagi hai, jaane kaisa noor hai",
      "Dekh ke chehra tera dil maghroor hai",
      "Roshni roshni har taraf ho gayi",
      "Zindagi ishq mein gumshuda ho gayi",
      "Husn-e-jaana ki tareef mumkin nahi",
      "Afreen afreen, afreen afreen...",
      "Tu bhi dekhe agar toh kahe humnasheen...",
      "✦ Celestial Pavilion Starlight Fade ✦"
    ]
  },
  {
    id: 10,
    title: "Arz Kia Hai",
    artist: "Anuv Jain X Lost Stories",
    album: "Coke Studio Bharat",
    worldName: "Warm Acoustic Studio",
    mood: "Intimate & Soulful",
    badge: "Studio Sessions",
    tagPhrase: "cozy corner",
    note: "Warm amber lamps, vintage microphones, and acoustic guitar strings. A cozy musical hug for you ♡",
    image: "assets/images/world_10.jpg",
    audioSrc: "assets/audio/track_10.mp3",
    quote: "Arz kiya hai... dil ke panne pe sirf tera hi zikr hai...",
    translation: "I present before you... upon every page of my heart, only your story is written...",
    lore: "Surrounded by vintage ribbon microphones, acoustic guitars, analog dials, and warm mood lighting in a cozy recording studio sanctuary.",
    theme: {
      primary: "#d97706",
      accent: "#fbbf24",
      bgGradient: "linear-gradient(135deg, #261608 0%, #3a220c 50%, #16101c 100%)",
      glowColor: "rgba(217, 119, 6, 0.45)"
    },
    audio: {
      ambientType: "vinyl_crackle"
    },
    lyrics: [
      "✦ Cozy Studio Guitar Fingerpicking ✦",
      "Arz kiya hai... dil ke panne pe sirf tera hi zikr hai",
      "Dheemi si aanch pe pighalta yeh fikar hai",
      "Acoustic strings whispering in the quiet room",
      "Your sweet fragrance cuts through the gloom",
      "Kash tu yahan mere paas baithi hoti",
      "Har baat pe muskurati, roti",
      "Yeh dastaan bas teri aur meri hai",
      "Raat bachi thodi, baat batheri hai...",
      "✦ Lost Stories Atmospheric Beat ✦",
      "Arz kiya hai, sun toh zara",
      "Dil ne jo kaha, samajh toh zara",
      "Khwaabon ki chhat pe taare gine hain",
      "Tere hi rangon se dhaage bune hain",
      "Arz kiya hai... dil ke panne pe sirf tera hi zikr hai",
      "Dheemi si aanch pe pighalta yeh fikar hai",
      "Yeh dastaan bas teri aur meri hai...",
      "Raat bachi thodi, baat batheri hai...",
      "Arz kiya hai... sun toh zara...",
      "✦ Vintage Vinyl Crackle Outro ✦"
    ]
  },
  {
    id: 11,
    title: "Bulleya",
    artist: "Papon",
    album: "Sultan (Vishal & Shekhar)",
    worldName: "Sufi Ruins Under Cosmic Trails",
    mood: "Spiritual & Majestic",
    badge: "Cosmic Sufi",
    tagPhrase: "soulful & free",
    note: "Campfire embers turning under a sky full of shooting star trails. When you need that burst of spiritual energy ♡",
    image: "assets/images/world_11.jpg",
    audioSrc: "assets/audio/track_11.mp3",
    quote: "Kaisi yeh lagan tu laga gaya hai, rasta yeh naya dikha gaya hai...",
    translation: "What divine devotion have you ignited, showing me an uncharted sacred path...",
    lore: "Ancient terracotta ruins in the heart of the desert where whirling cosmic star trails turn around a roaring sanctuary campfire under infinite skies.",
    theme: {
      primary: "#ea580c",
      accent: "#38bdf8",
      bgGradient: "linear-gradient(135deg, #2b1208 0%, #431b0c 50%, #0d1e33 100%)",
      glowColor: "rgba(234, 88, 12, 0.45)"
    },
    audio: {
      ambientType: "campfire_sparks"
    },
    lyrics: [
      "✦ Sufi Acoustic & Desert Wind Intro ✦",
      "Kaisi yeh lagan tu laga gaya hai",
      "Rasta yeh naya dikha gaya hai",
      "Tere teer ko kamaan mil gayi",
      "Meri rooh ko pehchan mil gayi",
      "Bulleya, Bulleya tu hi mera yaar",
      "Mera rab tu hi, tu hi sansaar",
      "Sufi whirling under the cosmic stars",
      "Healing the pain of ancient scars...",
      "✦ Campfire Sparks Rock Bridge ✦",
      "Jal rahi hai aag mere seene mein",
      "Maza aa raha hai ab jeene mein",
      "Mera dil meri jaan tere naam karoon",
      "Har sajde mein tera hi naam loon",
      "Bulleya, Bulleya tu hi mera yaar",
      "Mera rab tu hi, tu hi sansaar...",
      "✦ Whirling Desert Embers Fade ✦"
    ]
  },
  {
    id: 12,
    title: "Tose Naina",
    artist: "Arijit Singh",
    album: "Mickey Virus",
    worldName: "Monsoon Waters of Kerala",
    mood: "Serene & Romantic",
    badge: "Rainforest Mist",
    tagPhrase: "rainy afternoon",
    note: "Tropical raindrops falling on lotus leaves in emerald backwaters. The most peaceful sound in the world ♡",
    image: "assets/images/world_12.jpg",
    audioSrc: "assets/audio/track_12.mp3",
    quote: "Tose naina jab se mile, ban gaye silsile...",
    translation: "Ever since my eyes met yours, endless stories began to unfold...",
    lore: "Gliding through emerald backwaters shrouded in tropical monsoon mist, watching raindrops form rippling mandalas upon blooming water lilies.",
    theme: {
      primary: "#059669",
      accent: "#6ee7b7",
      bgGradient: "linear-gradient(135deg, #072218 0%, #0c3527 50%, #051811 100%)",
      glowColor: "rgba(5, 150, 105, 0.45)"
    },
    audio: {
      ambientType: "tropical_monsoon"
    },
    lyrics: [
      "✦ Tropical Raindrop Piano Intro ✦",
      "Tose naina jab se mile, ban gaye silsile",
      "Khwaabon ke aangan mein phool khile",
      "Raindrops fall gently on emerald leaves",
      "The heart softly whispers and believes",
      "Sudh-budh khoyi meri chain gawaaya",
      "Jab se tu mere sapnon mein aaya",
      "Tose naina jab se mile...",
      "✦ Kerala Backwater Monsoon Flute ✦",
      "Monsoon breeze carrying your scent afar",
      "Guiding me home like a northern star",
      "Teri nigaahon ne dil ko chhu liya",
      "Khamoshiyon ne sab keh diya",
      "Tose naina jab se mile, ban gaye silsile",
      "Khwaabon ke aangan mein phool khile",
      "Sudh-budh khoyi meri chain gawaaya...",
      "Jab se tu mere sapnon mein aaya...",
      "Ban gaye silsile... tose naina jab se mile...",
      "✦ Emerald Rain Mist Fade ✦"
    ]
  },
  {
    id: 13,
    title: "O Rangrez",
    artist: "Javed Bashir & Shreya Ghoshal",
    album: "Bhaag Milkha Bhaag",
    worldName: "Courtyard of Saffron & Indigo Silks",
    mood: "Passionate & Artisanal",
    badge: "Vivid Silk",
    tagPhrase: "colorful joy",
    note: "Swirling saffron, magenta, and indigo silks dancing in the afternoon sun. May your life be filled with all the bright colors ♡",
    image: "assets/images/world_13.jpg",
    audioSrc: "assets/audio/track_13.mp3",
    quote: "O rangrez, tere rang rang ke, tere rang rang ke, dhoop mein khile...",
    translation: "O master of colors, drench me in your hues so I blossom like dawn in the sun...",
    lore: "A sun-drenched heritage courtyard where vivid dyed saffron, crimson, and royal indigo silks flutter freely in golden afternoon sunbeams.",
    theme: {
      primary: "#f97316",
      accent: "#6366f1",
      bgGradient: "linear-gradient(135deg, #311508 0%, #461f0c 50%, #17153d 100%)",
      glowColor: "rgba(249, 115, 22, 0.5)"
    },
    audio: {
      ambientType: "breeze_flute"
    },
    lyrics: [
      "✦ Traditional Saffron Flute & Sitar Intro ✦",
      "O rangrez, tere rang rang ke...",
      "Dhoop mein khile, chhaon mein dhale",
      "Apne hi rang mein mujhko dhaal de",
      "Saffron and indigo silks unfurl in the breeze",
      "Echoing melodies that bring my heart to ease",
      "Ek hi boond mein saara samundar samaye",
      "Jab tu mere roobaroo aaye",
      "O rangrez, rangrez mere...",
      "✦ Classical Tabla & Sarangi Jugalbandi ✦",
      "Ghunghat utha ke jo dekha tera roop",
      "Mithhi lagne lagi sardiyon ki dhoop",
      "Tann man pe chha gaya kaisa yeh suroor",
      "Hone laga dil beqasoor",
      "Rang de chunariya prem ke rang mein",
      "Mera tann man dhoop mein khile",
      "O rangrez, tere rang rang ke...",
      "✦ Vibrant Silk Courtyard Swell ✦",
      "Apne hi rang mein mujhko dhaal de",
      "Ek hi boond mein saara samundar samaye",
      "Jab tu mere roobaroo aaye...",
      "O rangrez... rangrez mere...",
      "✦ Golden Afternoon Sunlight Fade ✦"
    ]
  },
  {
    id: 14,
    title: "Darkhaast",
    artist: "Arijit Singh & Sunidhi Chauhan",
    album: "Shivaay",
    worldName: "Nordic Fjord Aurora Borealis",
    mood: "Epic & Breath-taking",
    badge: "Emerald Aurora",
    tagPhrase: "northern lights",
    note: "Dancing ribbons of emerald and violet aurora lights over snowy fjords. Cinematic, breathless, and unforgettable ♡",
    image: "assets/images/world_14.jpg",
    audioSrc: "assets/audio/track_14.mp3",
    quote: "Meri aadat bana le anjaane mein hi sahi, meri darkhaast hai yeh...",
    translation: "Make me your habit even without knowing, this is my ardent plea to you...",
    lore: "Standing beside a crystalline Nordic fjord beneath the dancing ribbons of emerald and violet Northern Lights, reflecting off silent glacial peaks.",
    theme: {
      primary: "#10b981",
      accent: "#38bdf8",
      bgGradient: "linear-gradient(135deg, #06201a 0%, #0d3b31 50%, #091c2f 100%)",
      glowColor: "rgba(16, 185, 129, 0.5)"
    },
    audio: {
      ambientType: "aurora_drone"
    },
    lyrics: [
      "✦ Nordic Aurora Cello & Ambient Wind ✦",
      "Meri aadat bana le anjaane mein hi sahi",
      "Meri darkhaast hai yeh, meri darkhaast hai",
      "Aurora dancing across the icy night",
      "Bathed in the mystical emerald light",
      "Tham ja tu thodi der mere paas",
      "Bujha de mere dil ki yeh pyas",
      "Ishq ki aanch mein jalne de mujhe",
      "Apni baahon mein pighalne de mujhe...",
      "✦ Powerful Orchestral Fjord Swell ✦",
      "Raat ka aanchal tham jaane de",
      "Do dilon ko qareeb aane de",
      "Har fasana tere naam likh diya",
      "Apna vajood tere sang jod diya",
      "Meri aadat bana le anjaane mein hi sahi",
      "Meri darkhaast hai yeh, meri darkhaast hai",
      "✦ Sunidhi & Arijit Vocal Duet Bridge ✦",
      "Tham ja tu thodi der mere paas",
      "Bujha de mere dil ki yeh pyas",
      "Apni baahon mein pighalne de mujhe",
      "Meri darkhaast hai yeh...",
      "Meri darkhaast hai... darkhaast hai...",
      "Raat ka aanchal tham jaane de...",
      "✦ Glacial Aurora Borealis Fade ✦"
    ]
  },
  {
    id: 15,
    title: "Tere Bina Na Guzara E",
    artist: "Josh Brar ft. Kinza Hashmi",
    album: "Bunty Bains Productions",
    worldName: "Twilight Firefly Sanctuary",
    mood: "Poignant & Longing",
    badge: "Firefly Dusk",
    tagPhrase: "for quiet nights",
    note: "Thousands of tiny glowing fireflies in a quiet forest. You are the brightest light in every room you walk into ♡",
    image: "assets/images/world_15.jpg",
    audioSrc: "assets/audio/track_15.mp3",
    quote: "Tere bina na guzara ae, tu hi sahara ae...",
    translation: "Life cannot pass without you; you alone are the anchor of my universe...",
    lore: "A tranquil winding path through dense twilight pine trees, illuminated by thousands of twinkling fireflies rising gently into the cool night air.",
    theme: {
      primary: "#22c55e",
      accent: "#a855f7",
      bgGradient: "linear-gradient(135deg, #0e2417 0%, #153924 50%, #1e1131 100%)",
      glowColor: "rgba(34, 197, 94, 0.45)"
    },
    audio: {
      ambientType: "night_forest"
    },
    lyrics: [
      "✦ Twilight Firefly Acoustic Strings ✦",
      "Tere bina na guzara ae, tu hi sahara ae",
      "Pulsing fireflies illuminate the grove",
      "Guiding the path of our eternal love",
      "Akhiyan udeek diyan tenu saari raat",
      "Kadon hovegi mukammal apni mulaqat",
      "Dil diyan gallan tenu dassniyan ne",
      "Tere sang khushiyan vasniyan ne",
      "✦ Night Forest Melody Interlude ✦",
      "Tu hi meri rooh da kinara ae",
      "Tere bina na guzara ae, tu hi sahara ae",
      "Raatan lambiyan te din bechain",
      "Bas tera hi rasta takde ne nain",
      "Tere sang khushiyan vasniyan ne",
      "Tere bina na guzara ae...",
      "Tu hi sahara ae, tu hi sahara ae...",
      "✦ Firefly Starlight Fade ✦"
    ]
  },
  {
    id: 16,
    title: "Udaarian",
    artist: "Satinder Sartaaj",
    album: "Seasons of Sartaaj",
    worldName: "Golden Harvest Horizon",
    mood: "Uplifting & Free",
    badge: "Golden Flight",
    tagPhrase: "fly high",
    note: "Taking flight across endless golden fields with nothing holding you back. Always chase your wildest dreams ♡",
    image: "assets/images/world_16.jpg",
    audioSrc: "assets/audio/track_16.mp3",
    quote: "Laye ne udaarian, chhad de khumaarian...",
    translation: "We have taken flight towards the skies, leaving all earthbound worries behind...",
    lore: "Endless golden wheat fields rippling beneath a soft summer breeze, watching colorful vintage hot air balloons glide toward the horizon.",
    theme: {
      primary: "#eab308",
      accent: "#38bdf8",
      bgGradient: "linear-gradient(135deg, #2c2207 0%, #46370c 50%, #0d2638 100%)",
      glowColor: "rgba(234, 179, 8, 0.45)"
    },
    audio: {
      ambientType: "meadow_wind"
    },
    lyrics: [
      "✦ Golden Wheat Field Harmonium & Flute ✦",
      "Laye ne udaarian, chhad de khumaarian",
      "Wheat fields whispering under golden skies",
      "Watching dreams take flight before our eyes",
      "Panchhi wangu udd chale asmaan wal",
      "Chhad ke fikar sare beete hue kal de",
      "Khuliyan hawayan vich saah le zara",
      "Zindagi di mehak nu mehsoos kar zara",
      "Laye ne udaarian, chhad de khumaarian",
      "✦ Sartaaj Poetic Folk Symphony ✦",
      "Udd chalo, udd chalo ambran de paar",
      "Jitthe sajja hai kudrat da sansaar",
      "Rabb di raza vich raazi rahiye",
      "Har ik saah vich shukrana kahiye",
      "Laye ne udaarian, chhad de khumaarian",
      "Panchhi wangu udd chale asmaan wal",
      "Khuliyan hawayan vich saah le zara...",
      "Zindagi di mehak nu mehsoos kar zara...",
      "Laye ne udaarian... chhad de khumaarian...",
      "✦ Sunlit Balloon Horizon Outro ✦"
    ]
  },
  {
    id: 17,
    title: "Ranjheya Ve",
    artist: "Zain Zohaib",
    album: "Yratta Media",
    worldName: "Mustard Fields of Punjab",
    mood: "Devotional & Heartfelt",
    badge: "Sarson Bloom",
    tagPhrase: "warm & sweet",
    note: "Pure devotional folk magic. May your days be as bright and golden as yellow mustard blossoms in winter ♡",
    image: "assets/images/world_17.jpg",
    audioSrc: "assets/audio/track_17.mp3",
    quote: "Ranjheya ve, dil ditta tenu saunh...",
    translation: "O my eternal beloved, I have surrendered my heart to you forever...",
    lore: "Vibrant yellow mustard flower fields stretching to the horizon, glowing intensely under the warm crimson-gold rays of a Punjabi sunset.",
    theme: {
      primary: "#facc15",
      accent: "#f43f5e",
      bgGradient: "linear-gradient(135deg, #302607 0%, #4a3a0c 50%, #3b0d18 100%)",
      glowColor: "rgba(250, 204, 21, 0.45)"
    },
    audio: {
      ambientType: "sunset_harmonium"
    },
    lyrics: [
      "✦ Sarson Bloom Sunset Alaap ✦",
      "Ranjheya ve, dil ditta tenu saunh",
      "Mustard fields shining in crimson sunset glow",
      "Where sweet melodies of love endlessly flow",
      "Tere bina suni lagdi hai dharat saari",
      "Tu hi meri zindagi, tu hi jaan pyari",
      "Sajjna ve dholna tere naal ishq mera",
      "Har saah utte likheya naam tera",
      "Ranjheya ve, ranjheya ve...",
      "✦ Sufi Devotional Harmonium Swell ✦",
      "Ishq tere vich main taan jogan ban gayi",
      "Tere naina di galiyan di ronaq ban gayi",
      "Dil ditta tenu saunh, ranjheya ve",
      "Tere naal ishq mera, dholna ve",
      "Tere bina suni lagdi hai dharat saari",
      "Tu hi meri zindagi, tu hi jaan pyari...",
      "Ranjheya ve... ranjheya ve...",
      "Dil ditta tenu saunh...",
      "✦ Punjabi Sunset Crimson Echo ✦"
    ]
  },
  {
    id: 18,
    title: "Bairan",
    artist: "Banjaare / MC Square",
    album: "Bairan (Animated Love Story)",
    worldName: "Storm-Lashed Coastal Beacon",
    mood: "Fierce & Passionate",
    badge: "Tempest Beacon",
    tagPhrase: "storm & light",
    note: "A steady lighthouse in the middle of crashing stormy waves. No matter how stormy life gets, remember you have a light inside you ♡",
    image: "assets/images/world_18.jpg",
    audioSrc: "assets/audio/track_18.mp3",
    quote: "Bairan hawa kyun chali re, yaadan teri leke...",
    translation: "Why did the tempest wind blow, bringing with it echoes of your memory...",
    lore: "A towering historic stone lighthouse standing firm upon rugged sea cliffs as crashing stormy ocean waves send white mist into the dark sky.",
    theme: {
      primary: "#0ea5e9",
      accent: "#f43f5e",
      bgGradient: "linear-gradient(135deg, #091e2b 0%, #103348 50%, #20101b 100%)",
      glowColor: "rgba(14, 165, 233, 0.45)"
    },
    audio: {
      ambientType: "stormy_waves"
    },
    lyrics: [
      "✦ Coastal Tempest & Lighthouse Guitar ✦",
      "Bairan hawa kyun chali re, yaadan teri leke",
      "Crashing ocean tempest against the rocky shore",
      "Lighthouse beacon calling you once more",
      "Seene mein toofan jaise uth raha hai",
      "Har lamha teri yaadon mein dhal raha hai",
      "Kyun chhod gaye mujhko toofanon ke beech",
      "Aansuon ki nami meri palkan te kheench",
      "✦ Tempest Wave Bass Drop ✦",
      "Bairan hawa kyun chali re...",
      "Stormy winds howling through the deep night",
      "Searching the dark ocean for the lost light",
      "Yaadan teri leke, bairan hawa kyun chali re...",
      "✦ Storm Spray & Lighthouse Horn ✦"
    ]
  },
  {
    id: 19,
    title: "Wishes",
    artist: "Hasan Raheem ft. Talwiinder & Umair",
    album: "Wishes - Single",
    worldName: "Galaxy Observatory Summit",
    mood: "Contemplative & Infinite",
    badge: "Cosmic Wishes",
    tagPhrase: "make a wish",
    note: "A mountain observatory looking out into a deep violet galaxy. Make a silent wish on the stars tonight — it might just come true ♡",
    image: "assets/images/world_19.jpg",
    audioSrc: "assets/audio/track_19.mp3",
    quote: "I make wishes on the stars tonight, hope you see the same light...",
    translation: "Sending silent wishes across the celestial tapestry, trusting our paths intertwine...",
    lore: "A high-altitude stargazing observatory atop a silent mountain, looking out into a breathtaking deep violet galaxy with falling meteor trails.",
    theme: {
      primary: "#8b5cf6",
      accent: "#38bdf8",
      bgGradient: "linear-gradient(135deg, #18102b 0%, #261a45 50%, #0d1e38 100%)",
      glowColor: "rgba(139, 92, 246, 0.45)"
    },
    audio: {
      ambientType: "cosmic_starlight"
    },
    lyrics: [
      "✦ Cosmic Observatory Synth & Echoes ✦",
      "I make wishes on the stars tonight",
      "Hope you see the same starlight",
      "Observatory high above the clouds",
      "Far away from the rushing crowds",
      "Kash tu vi taareyan nu vekhdi hovein",
      "Mere baare thoda sochni hovein",
      "Cosmic nebula glowing in deep violet hues",
      "No more feeling lonely, no more blues",
      "✦ Starlight Space Trap Rhythm ✦",
      "Falling meteor trails across the dark",
      "Igniting within my soul a quiet spark",
      "I make wishes on the stars tonight",
      "Hope you see the same starlight",
      "Kash tu vi taareyan nu vekhdi hovein...",
      "Hoping everything turns out right...",
      "I make wishes on the stars tonight...",
      "✦ Deep Violet Galaxy Outro ✦"
    ]
  },
  {
    id: 20,
    title: "Kashish",
    artist: "Ashish Bhatia & Omkar Singh ft. Kashish",
    album: "Kashish - Official Video",
    worldName: "Futuristic Sky Lounge",
    mood: "Sophisticated & Velvet",
    badge: "Obsidian Twilight",
    tagPhrase: "for late night thoughts",
    note: "High above the sparkling city lights with amber warmth. The final world in this universe, but our story is just getting started ♡",
    image: "assets/images/world_20.jpg",
    audioSrc: "assets/audio/track_20.mp3",
    quote: "Yeh kashish dil ki jo hai, har lamha tera hi suroor hai...",
    translation: "This irresistible magnetic pull of the heart turns every passing moment into ecstasy...",
    lore: "An ultra-luxurious glass penthouse high above the glowing city lights at twilight, drinking in the quiet glamour of the boundless night.",
    theme: {
      primary: "#f59e0b",
      accent: "#ec4899",
      bgGradient: "linear-gradient(135deg, #1b131c 0%, #2c1a2e 50%, #12101b 100%)",
      glowColor: "rgba(245, 158, 11, 0.45)"
    },
    audio: {
      ambientType: "velvet_lounge"
    },
    lyrics: [
      "✦ Velvet Penthouse Sky Lounge Keys ✦",
      "Yeh kashish dil ki jo hai, har lamha tera hi suroor hai",
      "City lights bokeh sparkling in the night",
      "Velvet sky lounge bathed in amber light",
      "Tere bina jeena lagda ajeeb ae",
      "Tu hi mere dil de sab ton qareeb ae",
      "Magnetic attraction pulling us near",
      "Whispering secrets only we can hear",
      "✦ Lounge Saxophone & Bass Groove ✦",
      "Raat ka afsaana tere naam kiya hai",
      "Har ik pal tere ishq mein jiya hai",
      "Yeh kashish dil ki jo hai",
      "Har lamha tera hi suroor hai",
      "Tu hi mere dil de sab ton qareeb ae...",
      "Yeh kashish dil ki jo hai...",
      "Har lamha tera hi suroor hai...",
      "✦ City Bokeh Twilight Fade ✦"
    ]
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { SONGS_DATA, FINAL_MESSAGE };
}
